export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST"
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS"
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";

export const ADNIN_UPDATE_USER_REQUEST = "ADNIN_UPDATE_USER_REQUEST";
export const ADNIN_UPDATE_USER_SUCCESS = "ADNIN_UPDATE_USER_SUCCESS";
export const ADNIN_UPDATE_USER_RESET = "ADNIN_UPDATE_USER_RESET";
export const ADNIN_UPDATE_USER_FAIL = "ADNIN_UPDATE_USER_FAIL";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const ADNIN_DELETE_USER_REQUEST = "ADNIN_DELETE_USER_REQUEST";
export const ADNIN_DELETE_USER_SUCCESS = "ADNIN_DELETE_USER_SUCCESS";
export const ADNIN_DELETE_USER_REST = "ADNIN_DELETE_USER_REST";
export const ADNIN_DELETE_USER_FAIL = "ADNIN_DELETE_USER_FAIL";